language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

matrix:
  fast_finish: true

before_script:
  - composer install --no-interaction
  ./vendor/bin/phpcs -n --standard=PSR2 src/ tests/ --ignore=ExceptionErrorHandlerTest

script:
  - mkdir -p build/logs
  - php vendor/phpunit/phpunit/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/scrutinizer/ocular/bin/ocular code-coverage:upload --format=php-clover coverage.clover
